### PR TITLE
changed the api to check company

### PR DESCRIPTION
**Pull request by erickmgongo**
Guys the api changed a bit, i had to add eager loading to companies property in users entity.

Some one create another entity to be used in this case as i couldnt override the method to get users and change remove the company from responses

### CODE REVIEW

**Comment by BaharaJr** [comment]
Hello @erickmgongo I removed eager loading since it posses some performance issues when there is a lot of relationships.

**Comment by erickmgongo** [comment]
We are all set to go now, i used custom query. **NOTE:** i used public."user" as my table as user table in postgres returns default postgres user table with user postgres(bydefault/if you havent changed). Feel free to change if that doesnt work for your case.

**Comment by BaharaJr** [comment]
Hello @erickmgongo YES, you should always public.user or "user" to do that. I have finetuned the service and we should now be good to go. Cheers

**Comment by BaharaJr** [comment]
Hello @erickmgongo YES, you should always public.user or "user" to do that. I have finetuned the service and we should now be good to go. Cheers

**Comment by erickmgongo** [comment]
Great @BaharaJr

**Pull request merged**
